### ISSUE TITLE
Flutter upgrade

### ISSUE THREAD

**Issue by radikris** [sagarkarki99/simple_push_notification#6]
Could you update the packages version to be compatible with the latest Flutter version as well?

**Comment by rolandtolnay** [comment]
@radikris if you had the chance to solve this since then, could we get a PR with the change pls?
We are also blocked by this on our project atm

**Comment by radikris** [comment]
#7 @sagarkarki99 please check out this pr, it fixes this current issue.
Merge it if you can, because it blocks many people from upgrading.

**Comment by sagarkarki99** [comment]
Hey @radikris, 
Thank you for raising this issue. I will take a look into this. 
Apology for the late response.
